spring.application.name=demo-backend

# URL de connexion (ajoutez ?sslmode=require à la fin pour Neon)
spring.datasource.url=jdbc:postgresql://ep-snowy-heart-alsgzcsq-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_heRNUP4yS0YE

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG